#!/bin/bash
#PBS -q E 
#PBS -l select=2:ncpus=80:mpiprocs=4:ompthreads=20:mem=755gb
#PBS -N OpenSWPC-example
## -------------------------------------- ##
source /etc/profile.d/modules.sh
module load intel mpt lib/NetCDF lib/HDF5 
cd $PBS_O_WORKDIR
## -------------------------------------- ##
# OpenSWPCの構造モデル等の置き場の設定
export DATASET=/work/tktmyd/dataset  
## -------------------------------------- ##
mpiexec omplace -bs ./bin/swpc_3d.x -i example/input_NJapan.inf