#!/bin/csh

#$ -jc C                       # Job Class
#$ -ac n=32                    # Total Core
#$ -ac P=32                    # Total Core
#$ -cwd                        # Execute at the current directory
#$ -j y                        # Combine stderr & stdout
#$ -o swpc_out.txt             # Ouput filename
#$ -N SWPC                     # Job name

mpiexec_mpt -np 32 dplace -s1 ./bin/seism_3d.x -i example/input.inf
