#!/bin/sh
#PJM -L rscgrp=regular-flat
#PJM -L node=32
#PJM --mpi proc=32
#PJM --omp thread=66
#PJM -L elapse=00:30:00
#PJM -g SET-YOUR-GROUP-CODE
#PJM -j

module load hdf5 netcdf netcdf-fortran

#------ Pinning setting --------#
source /usr/local/bin/hybrid_core_setting.sh 2

#------- Program execution -------#
mpiexec.hydra -n ${PJM_MPI_PROC} numactl --preferred=1 ./bin/swpc_3d.x -i ./example/input.inf
